import type { WorkerStateLike } from "./state.js";
/**
 * Minimal VitestRunner for the in-page test runner.
 *
 * The runner callbacks are patched exactly like vitest's `resolveTestRunner`
 * (packages/vitest/src/runtime/runners/index.ts): onCollectStart → rpc.onQueued,
 * onCollected → rpc.onCollected (with retry-condition sanitization), and
 * onTaskUpdate → rpc.onTaskUpdate. This lets vitest's server-side state build
 * the reported task tree natively — no duck-typed TestModule/TestCase.
 */
import { collectTests, startTests } from "@vitest/runner";
import { createWorkerState } from "./state.js";

/**
 * Generated by the bundler: maps a source test file path (as passed by
 * vitest, with forward slashes) to the bundled artifact relative to the page.
 */
import manifest from "./tests-manifest.js";

export class ZoteroVitestRunner {
  config: Record<string, any>;
  pool = "zotero";
  viteEnvironment = "node";
  // reporting callbacks (patched by patchRunner, called by @vitest/runner)
  onTaskUpdate?: (tasks: unknown, events: unknown) => unknown;
  onCollectStart?: (file: unknown) => unknown;
  onCollected?: (files: any[]) => unknown;
  private readonly importDurations = new Map<string, { start: number; end: number }>();

  constructor(config: any) {
    this.config = {
      root: config.root || "/",
      setupFiles: [],
      name: undefined,
      passWithNoTests: false,
      testNamePattern: undefined,
      allowOnly: true,
      sequence: config.sequence || {
        shuffle: false,
        concurrent: false,
        seed: 0,
        hooks: "stack",
        setupFiles: "parallel",
      },
      chaiConfig: undefined,
      maxConcurrency: 10,
      testTimeout: config.testTimeout || 5000,
      hookTimeout: config.hookTimeout || 10000,
      retry: 0,
      includeTaskLocation: false,
      diffOptions: undefined,
      tags: [],
      tagsFilter: undefined,
      strictTags: false,
    };
  }

  /** Test files are pre-bundled by rolldown; map source path → artifact. */
  async importFile(filepath: string): Promise<void> {
    const start = performance.now();
    const rel = manifest[filepath];
    if (!rel) {
      throw new Error(`No bundled artifact for ${filepath}`);
    }
    await import(`./${rel}`);
    this.importDurations.set(filepath, { start, end: performance.now() });
  }

  getImportDurations(): Record<string, { start: number; end: number }> {
    return Object.fromEntries(this.importDurations);
  }
}

/**
 * Patches the runner's reporting callbacks to push updates over the rpc
 * channel, mirroring vitest's `resolveTestRunner`.
 */
export function patchRunner(runner: ZoteroVitestRunner, state: WorkerStateLike): void {
  const originalOnTaskUpdate = runner.onTaskUpdate;
  runner.onTaskUpdate = async (tasks: unknown, events: unknown) => {
    const p = state.rpc.onTaskUpdate(tasks, events);
    await originalOnTaskUpdate?.call(runner, tasks, events);
    return p;
  };

  const originalOnCollectStart = runner.onCollectStart;
  runner.onCollectStart = async (file: unknown) => {
    await state.rpc.onQueued(file);
    await originalOnCollectStart?.call(runner, file);
  };

  const originalOnCollected = runner.onCollected;
  runner.onCollected = async (files: any[]) => {
    files.forEach((file) => {
      file.prepareDuration = state.durations.prepare;
      file.environmentLoad = state.durations.environment;
      state.durations.prepare = 0;
      state.durations.environment = 0;
    });
    const sanitizeRetryConditions = (task: any) => {
      if (task.retry && typeof task.retry === "object" && typeof task.retry.condition === "function") {
        task.retry = { ...task.retry, condition: undefined };
      }
      if (task.tasks) {
        task.tasks.forEach(sanitizeRetryConditions);
      }
    };
    files.forEach(sanitizeRetryConditions);
    state.rpc.onCollected(files);
    await originalOnCollected?.call(runner, files);
  };
}

/**
 * Runs (or collects) the given files. Mirrors `runBaseTests`'s entry points:
 * `collectTests` for the collect phase, `startTests` for a full run.
 */
export async function runMethod(
  context: any,
  isCollect: boolean,
  state: WorkerStateLike,
): Promise<void> {
  const runner = new ZoteroVitestRunner(state.config);
  patchRunner(runner, state);
  if (isCollect) {
    const files = await collectTests(context.files, runner as any);
    await runner.onCollected?.(files);
  }
  else {
    await startTests(context.files, runner as any);
  }
}

export { createWorkerState };
