import type {
  RunnerTestFile,
  SerializedConfig,
  RunnerTaskEventPack as TaskEventPack,
  RunnerTaskResultPack as TaskResultPack,
} from "vitest";
import type { WorkerStateLike } from "./state.js";
import type { FileSpecification, RunContext } from "./types.js";
import { collectTests, startTests } from "vitest/internal/browser";
import { createWorkerState } from "./state.js";

/**
 * Generated by the bundler: maps a source test file path (as passed by
 * vitest, with forward slashes) to the bundled artifact relative to the page.
 */
import manifest from "./tests-manifest.js";

/** Fallback manifest baked into setup.js by the bundler (initial run). */
const bakedManifest = manifest;

/**
 * Minimal VitestRunner for the in-page test runner.
 *
 * The runner callbacks are patched exactly like vitest's `resolveTestRunner`
 * (packages/vitest/src/runtime/runners/index.ts): onCollectStart → rpc.onQueued,
 * onCollected → rpc.onCollected (with retry-condition sanitization), and
 * onTaskUpdate → rpc.onTaskUpdate. This lets vitest's server-side state build
 * the reported task tree natively — no duck-typed TestModule/TestCase.
 */

/**
 * The config subset the in-page runner exposes to @vitest/runner. Most fields
 * mirror SerializedConfig; `diffOptions` is a runtime-only field of vitest's
 * resolved config that the runner reads defensively.
 */
export type RunnerConfig = Partial<SerializedConfig> & {
  diffOptions?: unknown;
};

export class ZoteroVitestRunner {
  config: RunnerConfig;
  pool = "zotero";
  viteEnvironment = "node";
  // reporting callbacks (patched by patchRunner, called by @vitest/runner)
  onTaskUpdate?: (tasks: TaskResultPack[], events: TaskEventPack[]) => unknown;
  onCollectStart?: (file: RunnerTestFile) => unknown;
  onCollected?: (files: RunnerTestFile[]) => unknown;
  private readonly importDurations = new Map<string, { start: number; end: number }>();
  /**
   * Source path → bundled artifact. The run request carries the current
   * manifest (`context.testerManifest`) so watch-mode rebuilds (fresh stamp
   * artifact URLs) take effect without reloading the page; the manifest
   * baked into setup.js is the fallback for the initial run.
   */
  private readonly manifest: Record<string, string>;

  constructor(config: SerializedConfig, manifest?: Record<string, string>) {
    this.manifest = manifest ?? bakedManifest;
    this.config = {
      root: config.root || "/",
      // vitest runs setupFiles before each collected file (runner.importFile
      // with type "setup"); the bundler bakes them into the manifest like
      // test files, so they load from the bundled artifacts.
      setupFiles: config.setupFiles ?? [],
      // Must match the server's project name: file task ids are hashed from
      // `relative(root, filepath) + projectName`, and the server links the
      // collected task to the specification via that id. A mismatch (e.g.
      // `undefined` here while the project has a name) silently drops every
      // collected test module in projects mode ("No test files found").
      name: config.name,
      passWithNoTests: false,
      testNamePattern: undefined,
      allowOnly: true,
      sequence: config.sequence || {
        shuffle: false,
        concurrent: false,
        seed: 0,
        hooks: "stack",
        setupFiles: "parallel",
      },
      chaiConfig: undefined,
      maxConcurrency: 10,
      testTimeout: config.testTimeout || 5000,
      hookTimeout: config.hookTimeout || 10000,
      retry: 0,
      includeTaskLocation: false,
      diffOptions: undefined,
      tags: [],
      tagsFilter: undefined,
      strictTags: false,
    };
  }

  /** Test files are pre-bundled by rolldown; map source path → artifact. */
  async importFile(filepath: string, _type?: string): Promise<void> {
    const start = performance.now();
    const rel = this.manifest[filepath];
    if (!rel) {
      throw new Error(`No bundled artifact for ${filepath}`);
    }
    await import(`./${rel}`);
    this.importDurations.set(filepath, { start, end: performance.now() });
  }

  getImportDurations(): Record<string, { start: number; end: number }> {
    return Object.fromEntries(this.importDurations);
  }
}

/**
 * Patches the runner's reporting callbacks to push updates over the rpc
 * channel, mirroring vitest's `resolveTestRunner`.
 */
export function patchRunner(runner: ZoteroVitestRunner, state: WorkerStateLike): void {
  const originalOnTaskUpdate = runner.onTaskUpdate;
  runner.onTaskUpdate = async (tasks: TaskResultPack[], events: TaskEventPack[]) => {
    const p = state.rpc.onTaskUpdate(tasks, events);
    await originalOnTaskUpdate?.call(runner, tasks, events);
    return p;
  };

  const originalOnCollectStart = runner.onCollectStart;
  runner.onCollectStart = async (file: RunnerTestFile) => {
    await state.rpc.onQueued(file);
    await originalOnCollectStart?.call(runner, file);
  };

  const originalOnCollected = runner.onCollected;
  runner.onCollected = async (files: RunnerTestFile[]) => {
    files.forEach((file) => {
      file.prepareDuration = state.durations.prepare;
      file.environmentLoad = state.durations.environment;
      state.durations.prepare = 0;
      state.durations.environment = 0;
    });
    // The runner's task tree mixes suites (with children) and tests; the
    // recursion only needs `retry` + `tasks` from each node.
    type RetryableTask = RunnerTestFile & { tasks?: RetryableTask[] };
    const sanitizeRetryConditions = (task: RetryableTask) => {
      if (task.retry && typeof task.retry === "object"
        && typeof (task.retry as { condition?: unknown }).condition === "function") {
        task.retry = { ...task.retry, condition: undefined };
      }
      task.tasks?.forEach(child => sanitizeRetryConditions(child as RetryableTask));
    };
    files.forEach(file => sanitizeRetryConditions(file as RetryableTask));
    state.rpc.onCollected(files);
    await originalOnCollected?.call(runner, files);
  };
}

/**
 * Runs (or collects) the given files. Mirrors `runBaseTests`'s entry points:
 * `collectTests` for the collect phase, `startTests` for a full run.
 */
export async function runMethod(
  context: RunContext,
  isCollect: boolean,
  state: WorkerStateLike,
): Promise<void> {
  if (!state.config) {
    throw new Error("runMethod called before the start handshake");
  }
  const runner = new ZoteroVitestRunner(state.config, context.testerManifest);
  patchRunner(runner, state);
  const files: FileSpecification[] = context.files;
  // The runner duck-types vitest's VitestRunner (we mirror the callbacks it
  // invokes, not its full interface), so cast through unknown.
  const asVitestRunner = runner as unknown as Parameters<typeof startTests>[1];
  if (isCollect) {
    const collected = await collectTests(files, asVitestRunner);
    await runner.onCollected?.(collected);
  }
  else {
    await startTests(files, asVitestRunner);
  }
}

export { createWorkerState };
