/* eslint-disable */
// Code generated by the zotero vitest pool e2e prototype
var chromeHandle;

async function startup({ rootURI }, reason) {
  await Zotero.initializationPromise;
  const aomStartup = Components.classes[
    "@mozilla.org/addons/addon-manager-startup;1"
  ].getService(Components.interfaces.amIAddonManagerStartup);
  const manifestURI = Services.io.newURI(rootURI + "manifest.json");
  chromeHandle = aomStartup.registerChrome(manifestURI, [
    ["content", "zotero-test-e2e", rootURI + "content/"],
  ]);

  // Let the host HTTP server start before opening the test window.
  await Zotero.Promise.delay(1000);
  Services.ww.openWindow(
    null,
    "chrome://zotero-test-e2e/content/index.html?port=__PORT__",
    "Zotero Vitest Pool",
    "chrome,centerscreen,resizable=yes",
    {}
  );
}

function shutdown({}, reason) {
  if (reason === APP_SHUTDOWN) return;
  if (chromeHandle) {
    chromeHandle.destruct();
    chromeHandle = null;
  }
}
